// Révision du Code/04-react-vue-移动端/vue/02.VueCli/3.vue_comment/src/views/CommentList/index.vue
<template>
  <div>
    <h3 class="reply">评论回复：</h3>
    <h2 v-show="!comments.length">暂无评论，点击左侧添加评论！！！</h2>
    <ul class="list-group">
      <CommentItem
        v-for="comment in comments"
        :key="comment.id"
        :comment="comment"
      />
    </ul>
  </div>
</template>

<script>
import CommentItem from "./CommentItem";

// 哪个组件需要数据展示，就定义在哪里
export default {
  name: "CommentList",
  data() {
    return {
      comments: [
        { id: 1, name: "peihua", content: "i love jingge" },
        { id: 2, name: "jingge", content: "i love peihua" },
      ],
    };
  },
  mounted() {
    // 绑定事件
    this.$bus.$on("addComment", this.addComment);
    this.$bus.$on("delComment", this.delComment);
  },
  beforeDestroy() {
    // 绑定事件
    this.$bus.$off("addComment", this.addComment);
    this.$bus.$off("delComment", this.delComment);
  },
  methods: {
    addComment(name, content) {
      this.comments.unshift({
        id: Date.now(),
        name,
        content,
      });
    },
    delComment(id) {
      this.comments = this.comments.filter((comment) => comment.id !== id);
    },
  },
  components: {
    CommentItem,
  },
};
</script>

<style>
</style>

// Révision du Code/04-react-移动端/React内容集合/03-熊健-react/react全家桶/react代码/02.react_cli/02.react_comment/src/pages/CommentList/index.jsx
import { Component } from "react";
// 想要包有提示，需要在package.json中依赖项添加包的依赖
import PropTypes from "prop-types";
import CommentItem from "./components/CommentItem";

export default class CommentList extends Component {
  static propTypes = {
    comments: PropTypes.array.isRequired,
    delComment: PropTypes.func.isRequired,
  };

  render() {
    const { comments, delComment } = this.props;

    const display = comments.length ? "none" : "block";

    return (
      <div>
        <h3 className="reply">评论回复：</h3>
        <h2 style={{ display }}>暂无评论，点击左侧添加评论！！！</h2>
        <ul className="list-group">
          {comments.map((comment) => {
            return (
              <CommentItem
                key={comment.id}
                comment={comment}
                delComment={delComment}
              />
            );
          })}
        </ul>
      </div>
    );
  }
}
