// Révision du Code/04-react-移动端/React内容集合/熊健-react/react全家桶/react代码/03.react_router/src1/pages/Detail/index.jsx
import React, { Component } from "react";

export default class Detail extends Component {
  state = {
    details: [
      { id: 1, title: "message001", content: "message content001" },
      { id: 3, title: "message003", content: "message content003" },
      { id: 5, title: "message005", content: "message content005" },
    ],
  };
  render() {
    const id = +this.props.match.params.id;
    console.log(id);
    const detail = this.state.details.find((detail) => detail.id === id);
    console.log(detail);
    return (
      <ul>
        <li>id: {detail.id}</li>
        <li>title: {detail.title}</li>
        <li>content: {detail.content}</li>
      </ul>
    );
  }
}

// Révision du Code/react-vue-webpack-移动端/vue/02.VueCli/6.vue_router/src-1/views/Home/Message/Detail/index.vue
<template>
  <ul>
    <li>id: {{ message.id }}</li>
    <li>title: {{ message.title }}</li>
    <li>content: {{ message.content }}</li>
  </ul>
</template>

<script>
export default {
  name: "Detail",
  data() {
    return {
      messages: [
        { id: 1, title: "title001", content: "content001" },
        { id: 3, title: "title003", content: "content003" },
        { id: 5, title: "title005", content: "content005" },
      ],
    };
  },
  // mounted() {
  //   console.log(this.$route.params.id);
  // },
  computed: {
    message() {
      const id = +this.$route.params.id;
      const message = this.messages.find((message) => message.id === id);
      return message;
    },
  },
};
</script>

<style>
</style>
