// Révision du Code/04-react-移动端/React内容集合/03-熊健-react/react全家桶/react代码/02.react_cli/03.react_ajax/src/pages/Search/index.jsx
import React, { Component } from "react";
import PropTypes from "prop-types";
import { connect } from "react-redux";
import { setLoading, getUsers } from "../../redux/actions";

class Search extends Component {
  static propTypes = {
    getUsers: PropTypes.func.isRequired,
    setLoading: PropTypes.func.isRequired,
  };

  state = {
    searchName: "",
  };

  shouldComponentUpdate(props, state) {
    return state.searchName !== this.state.searchName;
  }

  handleChange = (e) => {
    this.setState({
      searchName: e.target.value.trim(),
    });
  };

  search = async () => {
    const { searchName } = this.state;
    if (!searchName) {
      alert("请输入搜索的名称");
      return;
    }
    // 更新loading
    this.props.setLoading(true);
    // 发送请求更新users
    await this.props.getUsers(searchName);
    this.props.setLoading(false);
  };

  render() {
    return (
      <section className="jumbotron">
        <h3 className="jumbotron-heading">Search Github Users</h3>
        <div>
          <input
            type="text"
            placeholder="enter the name you search"
            onChange={this.handleChange}
          />
          <button onClick={this.search}>Search</button>
        </div>
      </section>
    );
  }
}

export default connect(null, {
  setLoading,
  getUsers,
})(Search);

// 代码复习/react-vue-webpack-移动端/vue/02.VueCli/4.vue_ajax/src/views/Search/index.vue
<template>
  <section class="jumbotron">
    <h3 class="jumbotron-heading">Search Github Users</h3>
    <div>
      <input
        type="text"
        placeholder="enter the name you search"
        v-model="searchName"
      />
      <button @click="search">Search</button>
    </div>
  </section>
</template>

<script>
export default {
  name: "Search",
  data() {
    return {
      searchName: "",
    };
  },
  methods: {
    search() {
      const { searchName } = this;
      if (!searchName) {
        alert("请输入搜索名称");
        return;
      }
      // 将searchName传递List组件，由List组件去发送请求
      this.$bus.$emit("search", searchName);
    },
  },
};
</script>

<style>
</style>
